routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use Illuminate\Support\Facades\Input;

//Search
Route::get ( '/', function () {
    return view ( 'welcome' );
} );
Route::any ( '/search', function () {
    $q = Input::get ( 'q' );
    if($q !=''){
    $user = User::where ( 'name', 'LIKE', '%' . $q . '%' )->orWhere ( 'email', 'LIKE', '%' . $q . '%' )->get ();
    if (count ( $user ) > 0)
        return view ( 'welcome' )->withDetails ( $user )->withQuery ( $q );
    else
        return view ( 'welcome' )->withMessage ( 'No Details found. Try to search again !' );
}} );

Route::resource('front','FrontendController');
Route::get('/','FrontendController@index')->name('front.index');


//front pages
Route::get('/about','FrontendController@getAbout')->name('front.about');
Route::get('/service','FrontendController@getService')->name('front.service');
Route::get('/portfolio','FrontendController@getPortfolio')->name('front.portfolio');
Route::get('/ourteam','FrontendController@getOurteam')->name('front.ourteam');
Route::get('/contact','FrontendController@getContact')->name('front.contact');
Route::post('/save','FrontendController@saveform')->name('saveform');

Route::get('/blog','FrontendController@getBlog')->name('front.blog');

Route::get('/blog/{id}','FrontendController@blogShow')->name('fblog.show');

Route::get('/featured/{id}','FrontendController@featureshow')->name('feature.show');


Auth::routes();

Route::prefix('admin')->group(function(){

//backend dashboard
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/logout','Auth\LoginController@AdminLogout')->name('admin.logout');

//service
Route::resource('service','ServiceController');
Route::get('/service/destroy/{id}','ServiceController@destroy')->name('service.delete');

//For Team
Route::resource('team','TeamController');
Route::get('/team/destroy/{id}','TeamController@destroy')->name('team.delete');


//For Article
Route::resource ('slider','SliderController');
Route::get('/slider/destroy/{id}','SliderController@destroy')->name('slider.delete');

//For Featured Content
Route::resource('featured','FeaturedController');
Route::get('/featured/destroy/{id}','FeaturedController@destroy')->name('featured.delete');


//For Blog
Route::resource('blog','BlogController');
Route::get('/blog/destroy/{id}','BlogController@destroy')->name('blog.delete');


//slider
Route::resource ('slider','SliderController');
Route::get('/slider/destroy/{id}','SliderController@destroy')->name('slider.delete');

//mslider
Route::resource ('mslider','MsliderController');
Route::get('/mslider/destroy/{id}','MsliderController@destroy')->name('mslider.delete');

//Alltitle
Route::resource ('alltitle','AlltitleController');
Route::get('/alltitle/destroy/{id}','AlltitleController@destroy')->name('alltitle.delete');

///about paragraph
Route::get('/aboutpara','AboutController@paraindex')->name('aboutpara.index');
Route::get('/aboutpara/create','AboutController@paracreate')->name('aboutpara.create');
Route::post('/aboutpara','AboutController@parastore')->name('aboutpara.store');
Route::get('/aboutpara/destroy/{id}','AboutController@paradestroy')->name('aboutpara.destroy');
Route::get('/aboutpara/{id}/edit','AboutController@paraedit')->name('aboutpara.edit');
Route::put('/aboutpara/{id}','AboutController@paraupdate')->name('aboutpara.update');

//about numeric
Route::resource('numeric','about\NumericController');
Route::get('/numeric/destroy/{id}','about\NumericController@destroy')->name('numeric.delete');

//about approach
Route::resource('approach','about\ApproachController');
Route::get('/approach/destroy/{id}','about\ApproachController@destroy')->name('approach.delete');

//abutton about
Route::resource('abutton','about\AbuttonController');
Route::get('/abutton/destroy/{id}','about\AbuttonController@destroy')->name('abutton.delete');

//service value
Route::resource('value','Service\ValuesController');
Route::get('/value/destroy/{id}','Service\ValuesController@destroy')->name('value.delete');

//Note service
Route::resource('note','Service\NoteController');
Route::get('/note/destroy/{id}','Service\NoteController@destroy')->name('note.delete');

//for contact
Route::resource('contact','ContactController');
Route::get('/contact/destroy/{id}','ContactController@destroy')->name('contacts.delete');

//for Social Media
Route::resource('social','SocialController');
Route::get('/social/destroy/{id}','SocialController@destroy')->name('social.delete');

//for logo
Route::resource('logo','LogoController');

//for Copyright
Route::resource('copyright','CopyrightController');

});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slider;
class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $slider =Slider::all();
        return view('backend.slider.index')->withslider($slider);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('backend.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $slider = new Slider;
        // if ($request->hasFile('simage')){
        //     $image=$request->file('simage');
        //     $filename=time().'.'.$image->getClientOriginalExtension();
        //     $location=public_path('/backend/uploads/image/'.$filename);
        //     Image::make($image)->resize(80,90)->save($location);
        //     $slider->simage=$filename;
           
        // }
        $slider->stitle=$request->stitle;
        $slider->sdetail=$request->sdetail;
        $slider->i1name=$request->i1name;
        $slider->i1detail=$request->i1detail;
        $slider->i2name=$request->i2name;
        $slider->i2detail=$request->i2detail;
        $slider->i3name=$request->i3name;
        $slider->i3detail=$request->i3detail;
        $slider->save();
        return redirect()->route('slider.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $slider =Slider::find($id);
       return view('backend.slider.edit')->withslider($slider);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::find($id);
        // if ($request->hasFile('simage')){
        //     $image=$request->file('simage');
        //     $filename=time().'.'.$image->getClientOriginalExtension();
        //     $location=public_path('/backend/uploads/image/'.$filename);
        //     Image::make($image)->resize(80,90)->save($location);
        //     $slider->simage=$filename;
           
        // }
        $slider->stitle=$request->stitle;
        $slider->sdetail=$request->sdetail;
        $slider->i1name=$request->i1name;
        $slider->i1detail=$request->i1detail;
        $slider->i2name=$request->i2name;
        $slider->i2detail=$request->i2detail;
        $slider->i3name=$request->i3name;
        $slider->i3detail=$request->i3detail;
        $slider->save();
        return redirect()->route('slider.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider=slider::find($id);
        $slider->delete();
        return redirect()->route('slider.index');
    }
}

resources/views/backend/slider/create.blade.php
@extends('backend.main')

@section('title','| Slider')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Slider Form Add
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="iconsmind-Library"></i></a></li>
        <li class="breadcrumb-item"><a href="{{route('slider.index')}}">List all</a></li>
        <li class="breadcrumb-item active"><a href="{{route('slider.create')}}">Create</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
     
     <!-- Basic Forms -->
      <div class="box box-solid box-primary">
        <div class="box-header with-border">
          <h6 class="box-subtitle text-white">Slider Create Form</h6>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col">
            {{Form::open(['route'=>'slider.store','method'=>'POST','files'=>'true','data-parsley-validate'=>''])}}
				
            <div class="form-group">
                <h5>Title:<span class="text-danger">*</span></h5>
                <div class="controls">
                <Input type="text" name="stitle" class="form-control"  placeholder="slider title...." required>
                </div>
              </div>


        <div class="form-group">
          <h5>Slider Detail: <span class="text-danger">*</span></h5>
          <div class="controls">
							<textarea name="sdetail"  id="editor1" rows="4" cols="50" placeholder="Slider Detail..." required data-validation-required-message="This field is required"></textarea> </div>

        </div>

        <div class="form-group">
            <h5>Icon:<span class="text-danger">*</span></h5>
            <div class="controls">
            <Input type="text" name="i1name" class="form-control"  placeholder="slider icon name...." required>
            </div>
          </div>

          <div class="form-group">
            <h5>Icon Detail: <span class="text-danger">*</span></h5>
            <div class="controls">
                              <textarea name="i1detail"  id="editor2" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required"></textarea> </div>
  
          </div>
          <div class="form-group">
              <h5>Icon:<span class="text-danger">*</span></h5>
              <div class="controls">
              <Input type="text" name="i2name" class="form-control"  placeholder="slider icon name...." required>
              </div>
            </div>
  
            <div class="form-group">
              <h5>Icon Detail: <span class="text-danger">*</span></h5>
              <div class="controls">
                                <textarea name="i2detail"  id="editor3" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required"></textarea> </div>
    
            </div>
            <div class="form-group">
                <h5>Icon:<span class="text-danger">*</span></h5>
                <div class="controls">
                <Input type="text" name="i3name" class="form-control"  placeholder="slider icon name...." required>
                </div>
              </div>
    
              <div class="form-group">
                <h5>Icon Detail: <span class="text-danger">*</span></h5>
                <div class="controls">
                                  <textarea name="i3detail"  id="editor4" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required"></textarea> </div>
      
              </div>

          {{-- <div class="form-group">
            <h5>Image:<span class="text-danger">*</span></h5>
            <div class="controls">
       <input type="file" name="simage" class="form-control" required> </div>
        </div> --}}
        {{-- <div class="form-group">
                <h5>Image2:<span class="text-danger">*</span></h5>
                <div class="controls">
           <input type="file" name="simage2" class="form-control" required> </div>
            </div>  
            <div class="form-group">
                    <h5>Image3:<span class="text-danger">*</span></h5>
                    <div class="controls">
               <input type="file" name="simage3" class="form-control" required> </div>
                </div> --}}

      
            {{Form::submit('submit',['class'=>'form-control'])}}
            {{Form::close()}}
          </div>
        </div></div></div></section></div>
@endsection

resources/views/backend/slider/edit.blade.php
@extends('backend.main')

@section('title','| Slider')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Slider Form Edit
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="iconsmind-Library"></i></a></li>
        <li class="breadcrumb-item"><a href="{{route('slider.index')}}"> List All</a></li>
        <li class="breadcrumb-item active"><a href="{{route('value.create')}}">Create</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
     
     <!-- Basic Forms -->
      <div class="box box-solid box-primary">
        <div class="box-header with-border">
          <h6 class="box-subtitle text-white">Edit Slider </h6>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col">
            {{Form::model($slider,['route'=>'slider.store','method'=>'POST','files'=>'true','data-parsley-validate'=>''])}}
				
            <div class="form-group">
                <h5>Title:<span class="text-danger">*</span></h5>
                <div class="controls">
                <Input type="text" name="stitle" value="{{$slider->stitle}}"class="form-control"  placeholder="slider title...." required>
                </div>
              </div>


        <div class="form-group">
          <h5>Slider Detail: <span class="text-danger">*</span></h5>
          <div class="controls">
							<textarea name="sdetail"  id="editor1" rows="4" cols="50" placeholder="Slider Detail..." required data-validation-required-message="This field is required">{{$slider->sdetail}}</textarea> </div>

        </div>

        <div class="form-group">
            <h5>Icon:<span class="text-danger">*</span></h5>
            <div class="controls">
            <Input type="text" name="i1name" class="form-control" value="{{$slider->i1name}}" placeholder="slider icon name...." required>
            </div>
          </div>

          <div class="form-group">
            <h5>Icon Detail: <span class="text-danger">*</span></h5>
            <div class="controls">
                              <textarea name="i1detail"  id="editor2" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required">{{$slider->i1detail}}</textarea> </div>
  
          </div>
          <div class="form-group">
              <h5>Icon:<span class="text-danger">*</span></h5>
              <div class="controls">
              <Input type="text" name="i2name" class="form-control" value="{{$slider->i2name}}" placeholder="slider icon name...." required>
              </div>
            </div>
  
            <div class="form-group">
              <h5>Icon Detail: <span class="text-danger">*</span></h5>
              <div class="controls">
                                <textarea name="i2detail"  id="editor3" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required">{{$slider->i2detail}}</textarea> </div>
    
            </div>
            <div class="form-group">
                <h5>Icon:<span class="text-danger">*</span></h5>
                <div class="controls">
                <Input type="text" name="i3name" class="form-control" value="{{$slider->i3name}}"  placeholder="slider icon name...." required>
                </div>
              </div>
    
              <div class="form-group">
                <h5>Icon Detail: <span class="text-danger">*</span></h5>
                <div class="controls">
                                  <textarea name="i3detail"  id="editor4" rows="4" cols="50" placeholder="Describe icon detail..." required data-validation-required-message="This field is required">{{$slider->i3detail}}</textarea> </div>
      
              </div>

          {{-- <div class="form-group">
            <h5>Image:<span class="text-danger">*</span></h5>
            <div class="controls">
            <img src="{{asset('backend/uploads/image/'.$slider->simage)}}" alt="">
       <input type="file" name="simage" class="form-control" > </div>
        </div> --}}
        {{-- <div class="form-group">
                <h5>Image2:<span class="text-danger">*</span></h5>
                <div class="controls">
                <img src="{{asset('backend/uploads/image/'.$slider->simage2)}}" alt="">
           <input type="file" name="simage2" class="form-control" required> </div>
            </div>  
            <div class="form-group">
                    <h5>Image3:<span class="text-danger">*</span></h5>
                    <div class="controls">
                    <img src="{{asset('backend/uploads/image/'.$slider->simage3)}}" alt="">
               <input type="file" name="simage3" class="form-control" required> </div>
                </div> --}}

      
            {{Form::submit('submit',['class'=>'form-control'])}}
            {{Form::close()}}
          </div>
        </div></div></div></section></div>
@endsection

resources/views/backend/slider/index.blade.php
@extends('backend.main')

@section('content')

<div class="content-wrapper">
  <div class="content">
         <div class="box box-solid box-primary">
            <div class="box-header with-border">
              <h4 class="box-title">slider List Data Table</h4>
              <h6 class="box-subtitle text-white-50">Export data to Copy, CSV, Excel, PDF & Print</h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
				<div class="table-responsive">
				  <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
              <thead>
                  <tr>
                    <th>S.N</th>  
                    <th>Title</th>
                    <th>TDetail</th>
                    <th>I1</th>
                    <th>I1d</th>
                    <th>I2</th>
                    <th>I2d</th>
                    <th>I3</th>
                    <th>I3d</th>
                   <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach($slider as $slider)
                     <tr>
                       <td>{{$loop->index+1}}</td>
                       <td>{{$slider->stitle}}</td>
                       <td>{!!$slider->sdetail!!}</td>
                     <td>{{$slider->i1name}}</td>
                     {{-- <td>{!!substr($slider->description,0,5)!!}{{strlen($slider->description)>2?"...":""}}</td> --}}
                     <td>{!!$slider->i1detail!!}{{strlen($slider->i1detail)>2?"...":""}}</td>
                     <td>{{$slider->i2name}}</td>
                     <td>{!!$slider->i2detail!!}{{strlen($slider->i2detail)>2?"...":""}}</td>
                     <td>{{$slider->i3name}}</td>
                     <td>{!!$slider->i3detail!!}{{strlen($slider->i3detail)>2?"...":""}}</td>

                       <td>
                          {{-- <a href="{{route('slider.edit',$slider->id)}}" class="btn btn-primary">Edit</a> --}}
                          <a href="{{route('slider.edit',$slider->id)}}" class="icon"><i class="fa fa-edit fa-2x text-info"></i></a>&nbsp;&nbsp;
                          <a  href="javascript:" rel="{{$slider->id}}" rel1="admin/slider/destroy" class="text-inverse deleteRecord" title="Delete" data-toggle="tooltip" data-original-title="Delete">
                            <i class="fa fa-trash fa-2x text-danger "></i>
                        </a>
                         
                         
        
                         
                         </td>
                     </tr>
                     @endforeach
                   </tbody>
				
				</table>
				</div>              
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->          
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
</div>
</div>
@endsection